const { getMaxListeners } = require("./user");

module.exports = 
[
    {
        userImg: "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/peaky-blinders-tom-hardy-1-2-1565013406.jpg?crop=0.481xw:0.728xh;0.207xw,0&resize=480:*",
        username: "Alfie Solomons",
        email: "samSam@gmail.com",
        password: "abc123",
        horse: [{
            horseImg: "https://is3-ssl.mzstatic.com/image/thumb/Purple125/v4/c0/4c/dd/c04cdd3f-baa9-f1d8-0bc3-6b6fae23497c/source/256x256bb.jpg",
            horseName: "John",
            breed: "Breed",
            height: 72,
            color: "brown",
            number: 4,
            horseShoe: "Aluminum",
            jockeyName: "Joe",
        },{
            horseImg: "https://is3-ssl.mzstatic.com/image/thumb/Purple125/v4/c0/4c/dd/c04cdd3f-baa9-f1d8-0bc3-6b6fae23497c/source/256x256bb.jpg",
            horseName: "Peter",
            breed: "Breed2",
            height: 71,
            color: "white",
            number: 5,
            horseShoe: "Aluminum",
            jockeyName: "John", 
        }],
    },
    {   
        userImg: "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/peaky-blinders-1614180392.jpg?resize=640:*",
        username: "Thomas Shelby",
        email: "tom@gmail.com",
        password: "abc123",
        horse: [{
            horseImg: "https://is3-ssl.mzstatic.com/image/thumb/Purple125/v4/c0/4c/dd/c04cdd3f-baa9-f1d8-0bc3-6b6fae23497c/source/256x256bb.jpg",
            horseName: "Sam",
            breed: "Breed3",
            height: 72,
            color: "brown",
            number: 4,
            horseShoe: "Aluminum",
            jockeyName: "Joe",
        },{
            horseImg: "https://is3-ssl.mzstatic.com/image/thumb/Purple125/v4/c0/4c/dd/c04cdd3f-baa9-f1d8-0bc3-6b6fae23497c/source/256x256bb.jpg",
            horseName: "Victor",
            breed: "Breed2",
            height: 71,
            color: "white",
            number: 5,
            horseShoe: "Aluminum",
            jockeyName: "John", 
        }],
    },
    {   
        userImg: "https://i2-prod.devonlive.com/incoming/article6493745.ece/ALTERNATES/s1200c/1_Screenshot-2022-01-14-at-140939.png",
        username: "Billy Kimber",
        email: "billy@gmail.com",
        password: "abc123",
        horse: [{
            horseImg: "https://is3-ssl.mzstatic.com/image/thumb/Purple125/v4/c0/4c/dd/c04cdd3f-baa9-f1d8-0bc3-6b6fae23497c/source/256x256bb.jpg",
            horseName: "Kim",
            breed: "Breed6",
            height: 72,
            color: "brown",
            number: 4,
            horseShoe: "Aluminum",
            jockeyName: "Joe",
        },{
            horseImg: "https://is3-ssl.mzstatic.com/image/thumb/Purple125/v4/c0/4c/dd/c04cdd3f-baa9-f1d8-0bc3-6b6fae23497c/source/256x256bb.jpg",
            horseName: "George",
            breed: "Breed5",
            height: 71,
            color: "white",
            number: 5,
            horseShoe: "Aluminum",
            jockeyName: "John", 
        }],
    },
    {   
        userImg: "https://preview.redd.it/xzsmbhapw0e51.png?auto=webp&s=eec3a069db7beda05b9481e33256d12224a9a52f",
        username: "Oswald Mosley",
        email: "oswald@gmail.com",
        password: "abc123",
        horse: [{
            horseImg: "https://is3-ssl.mzstatic.com/image/thumb/Purple125/v4/c0/4c/dd/c04cdd3f-baa9-f1d8-0bc3-6b6fae23497c/source/256x256bb.jpg",
            horseName: "Kim",
            breed: "Breed6",
            height: 72,
            color: "brown",
            number: 4,
            horseShoe: "Aluminum",
            jockeyName: "Joe",
        },{
            horseImg: "https://is3-ssl.mzstatic.com/image/thumb/Purple125/v4/c0/4c/dd/c04cdd3f-baa9-f1d8-0bc3-6b6fae23497c/source/256x256bb.jpg",
            horseName: "George",
            breed: "Breed5",
            height: 71,
            color: "white",
            number: 5,
            horseShoe: "Aluminum",
            jockeyName: "John", 
        }],
    },
    {   
        userImg: "https://www.personality-database.com/profile_images/124906.png",
        username: "Darby Sabini",
        email: "sabini@gmail.com",
        password: "abc123",
        horse: [{
            horseImg: "https://is3-ssl.mzstatic.com/image/thumb/Purple125/v4/c0/4c/dd/c04cdd3f-baa9-f1d8-0bc3-6b6fae23497c/source/256x256bb.jpg",
            horseName: "Kim",
            breed: "Breed6",
            height: 72,
            color: "brown",
            number: 4,
            horseShoe: "Aluminum",
            jockeyName: "Joe",
        },{
            horseImg: "https://is3-ssl.mzstatic.com/image/thumb/Purple125/v4/c0/4c/dd/c04cdd3f-baa9-f1d8-0bc3-6b6fae23497c/source/256x256bb.jpg",
            horseName: "George",
            breed: "Breed5",
            height: 71,
            color: "white",
            number: 5,
            horseShoe: "Aluminum",
            jockeyName: "John", 
        }],
    },
]