const { getMaxListeners } = require("./user");

module.exports = 
[
    {
        userImg: "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/peaky-blinders-tom-hardy-1-2-1565013406.jpg?crop=0.481xw:0.728xh;0.207xw,0&resize=480:*",
        bio: "Alfred 'Alfie' Solomons Jr. is a Jewish gang leader who resided in Camden Town, London. It is implied that Alfie's mother was a Russian refugee, where his mother was from and he went to school in London with Darby Sabini.",
        username: "Alfie Solomons",
        email: "samSam@gmail.com",
        password: "abc123",
        horse: [{
            horseImg: "https://is3-ssl.mzstatic.com/image/thumb/Purple125/v4/c0/4c/dd/c04cdd3f-baa9-f1d8-0bc3-6b6fae23497c/source/256x256bb.jpg",
            horseName: "Bella",
            breed: "Arabian",
            height: 72,
            color: "brown",
            number: 4,
            horseShoe: "Aluminum",
            jockeyName: "Joe",
        },{
            horseImg: "https://is3-ssl.mzstatic.com/image/thumb/Purple125/v4/c0/4c/dd/c04cdd3f-baa9-f1d8-0bc3-6b6fae23497c/source/256x256bb.jpg",
            horseName: "Alex",
            breed: "Appaloosa",
            height: 71,
            color: "Black/White",
            number: 5,
            horseShoe: "Steel",
            jockeyName: "John", 
        }],
    },
    {   
        userImg: "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/peaky-blinders-1614180392.jpg?resize=640:*",
        bio: "Thomas Michael 'Tommy' Shelby OBE DCM MM MP is the son of Arthur and Mrs. Shelby, brother of Arthur, John, Ada and Finn Shelby, father of Charles and Ruby Shelby, as well as being the husband of Grace and Lizzie Shelby. He is the leader of the Birmingham criminal gang, the Peaky Blinders and the patriarch of the Shelby Family.",
        username: "Thomas Shelby",
        email: "tom@gmail.com",
        password: "abc123",
        horse: [{
            horseImg: "https://is3-ssl.mzstatic.com/image/thumb/Purple125/v4/c0/4c/dd/c04cdd3f-baa9-f1d8-0bc3-6b6fae23497c/source/256x256bb.jpg",
            horseName: "Lilly",
            breed: "Thoroughbred",
            height: 70,
            color: "Grey",
            number: 10,
            horseShoe: "Aluminum",
            jockeyName: "Samuel",
        },{
            horseImg: "https://is3-ssl.mzstatic.com/image/thumb/Purple125/v4/c0/4c/dd/c04cdd3f-baa9-f1d8-0bc3-6b6fae23497c/source/256x256bb.jpg",
            horseName: "Victor",
            breed: "Standardbred",
            height: 71,
            color: "Beige",
            number: 21,
            horseShoe: "Aluminum",
            jockeyName: "George", 
        }],
    },
    {   
        userImg: "https://i2-prod.devonlive.com/incoming/article6493745.ece/ALTERNATES/s1200c/1_Screenshot-2022-01-14-at-140939.png",
        bio: "William 'Billy' Kimber was an English gangster and head of the Birmingham Boys and thus, the main enemy of Thomas Shelby and the Peaky Blinders. He ran most of the legal tracks outside of London, leading to tensions between Kimber and the Peaky Blinders, who looked to expand their control into inner city London.",
        username: "Billy Kimber",
        email: "billy@gmail.com",
        password: "abc123",
        horse: [{
            horseImg: "https://is3-ssl.mzstatic.com/image/thumb/Purple125/v4/c0/4c/dd/c04cdd3f-baa9-f1d8-0bc3-6b6fae23497c/source/256x256bb.jpg",
            horseName: "Sugar",
            breed: "Appaloosa",
            height: 73,
            color: "White",
            number: 15,
            horseShoe: "Steel",
            jockeyName: "Mike",
        },{
            horseImg: "https://is3-ssl.mzstatic.com/image/thumb/Purple125/v4/c0/4c/dd/c04cdd3f-baa9-f1d8-0bc3-6b6fae23497c/source/256x256bb.jpg",
            horseName: "Tucker",
            breed: "Akhal-Teke",
            height: 70,
            color: "Brown",
            number: 7,
            horseShoe: "Aluminum",
            jockeyName: "John", 
        }],
    },
    {   
        userImg: "https://preview.redd.it/xzsmbhapw0e51.png?auto=webp&s=eec3a069db7beda05b9481e33256d12224a9a52f",
        bio: "Sir Oswald Mosley is the Minister of the Duchy of Lancaster, the deputy to the Chancellor of the Exchequer and the Cabinet adviser to the Prime Minister of Great Britain. He is also the MP for Smethwick, the constituency bordering South Birmingham, [Shelby]'s constituency. Serving as the main antagonist of Season 5, he is described as the devil and is closely under the supervision of the Peaky Blinders.",
        username: "Oswald Mosley",
        email: "oswald@gmail.com",
        password: "abc123",
        horse: [{
            horseImg: "https://is3-ssl.mzstatic.com/image/thumb/Purple125/v4/c0/4c/dd/c04cdd3f-baa9-f1d8-0bc3-6b6fae23497c/source/256x256bb.jpg",
            horseName: "Jill",
            breed: "Thoroughbred",
            height: 72,
            color: "Brown",
            number: 41,
            horseShoe: "Steel",
            jockeyName: "Jessica",
        },{
            horseImg: "https://is3-ssl.mzstatic.com/image/thumb/Purple125/v4/c0/4c/dd/c04cdd3f-baa9-f1d8-0bc3-6b6fae23497c/source/256x256bb.jpg",
            horseName: "Morgan",
            breed: "Standardbred",
            height: 73,
            color: "White",
            number: 23,
            horseShoe: "Aluminum",
            jockeyName: "Stephanie", 
        }],
    },
    {   
        userImg: "https://www.personality-database.com/profile_images/124906.png",
        bio: "Charles 'Darby' Sabini born Ottavio Handley Sabini (11 July 1888 - 4 October 1950) is a British Italian gang leader from London, England. He was at war with Alfie Solomons and Thomas Shelby in Series 2. Darby Sabini serves as the secondary antagonist of the second series.",
        username: "Darby Sabini",
        email: "sabini@gmail.com",
        password: "abc123",
        horse: [{
            horseImg: "https://is3-ssl.mzstatic.com/image/thumb/Purple125/v4/c0/4c/dd/c04cdd3f-baa9-f1d8-0bc3-6b6fae23497c/source/256x256bb.jpg",
            horseName: "Hank",
            breed: "American Quater Horse",
            height: 71,
            color: "Black",
            number: 31,
            horseShoe: "Aluminum",
            jockeyName: "Joe",
        },{
            horseImg: "https://is3-ssl.mzstatic.com/image/thumb/Purple125/v4/c0/4c/dd/c04cdd3f-baa9-f1d8-0bc3-6b6fae23497c/source/256x256bb.jpg",
            horseName: "Lady",
            breed: "Arabian horse",
            height: 70,
            color: "Brown",
            number: 9,
            horseShoe: "Steel",
            jockeyName: "Haley", 
        }],
    },
]